name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ..

      - name: Build and test
        run: |
          cd client
          npm run build
          cd ..

      - name: Deploy to production
        run: |
          # Add deployment steps here
